export const panelTypeConstant = {
  PANEL_CREATE_DOCTOR: 'PANEL_CREATE_DOCTOR',
  PANEL_CREATE_PATIENT: 'PANEL_CREATE_PATIENT',
  PANEL_EDIT_PATIENT: 'PANEL_EDIT_PATIENT',

  PANEL_CREATE_DISEASES: "PANEL_CREATE_DISEASES",
  PANEL_EDIT_DISEASES: "PANEL_EDIT_DISEASES",

  PANEL_CREATE_MEDICATION: "PANEL_CREATE_MEDICATION",
  PANEL_EDIT_MEDICATION: "PANEL_EDIT_MEDICATION"
}