export {default as Logo} from "./logo.png"
export {default as LogoSidebar} from "./logosidebar.png"
export {default as HomePic1} from "./homepage pic 1.jpg"
export {default as HomePic2} from "./homepage pic 2.png"
export {default as dataNotFound} from "./dataNotFound.png"
export {default as info} from "./info.png"
export {default as warning} from "./warning.png"
export {default as error} from "./error.png"
export {default as success} from "./success.png"